name: Download Code Repo
on:  push

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List files after
        run: ls -a
      
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path:
            app.js