name: Download Code Repo
on:  

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List files after
        run: ls -a